### ISSUE TITLE
How to merge multiple ts input into one output?

### ISSUE THREAD

**Issue by ashiskumarsahu** [futzu/x9k3#12]
I have 5 ts file such as
test_1.ts
test_2.ts
test_3.ts
test_4.ts

I want to pragmatically parse each ts file but my output should be in one directory and one **index.m3u8** should created. It like appending to one file.

Below is the sample code but its not working as currently I don't know how to do this.
`
import x9k3
for ts in multiple_ts:
    x9 = x9k3.X9K3(ts)
    x9.args.output_dir="output/"
    x9.run()
`

Thank you

**Comment by ashiskumarsahu** [comment]
Hi @futzu,
I am trying to develop a pipeline where I can take multiple mpegts as input and pass to x9k3.
Could you please suggest how to achieve the following scenario?

`
fmpeg -i original.mkv
-c:v h264 -c:a aac -f mpegts - | myprogam \
-c:v h264 -c:a aac -vf "scale=1280:720" -f mpegts - | myprogam \
-c:v h264 -c:a aac -vf "scale=854:480" -f mpegts - | myprogam \
`
I have tried passing all version of mpegts to a python program with a pipe like below,
`
fmpeg -i original.mkv -c:v h264 -c:a aac -f mpegts -  \
-c:v h264 -c:a aac -vf "scale=1280:720" -f mpegts -  \
-c:v h264 -c:a aac -vf "scale=854:480" -f mpegts - | myprogam 
`
At python end I am unable to read them separately with stdin.
Can you help here?

Thank you

**Comment by futzu** [comment]
I understand what you're saying, but that will not work, you're just merging the outputs together.
You may feel like you're close, but ABR makes things  complicated.
There is a good bit more to it. 

You seem new to video and I don't think you realize everything involved/

As I have said, If you want to hire me, I will work it out for you.
We have been discussing this for at least a month, 
I could have you up and running in two weeks.

**Comment by futzu** [comment]
I am not trying to be mean when I say this, but you are not close to a solution.
You are not just about to figure it out.
 Your methodology has not changed, you just changed to format of the output from m3u8 to mpegts.
You keep asking the same question and I keep giving you the same answer.


I said it would take me two weeks,
because it would take me two weeks of work 
to do it. 
I am closing this because it's not an x9k3 issue.
