### ISSUE TITLE
SCTE-OUT/IN pairs inside EXT-X-DATERANGE do not have the same ID, as the standard says

### ISSUE THREAD

**Issue by chreniuc** [futzu/x9k3#19]
The hls standard states that:

>An SCTE-35 splice out/in pair signaled by a pair of splice_insert()
   commands SHOULD be represented by one or more EXT-X-DATERANGE tags
   carrying the same ID attribute, which MUST be unique to that splice
   out/in pair.

https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.5.1.1

This tool generates that pair with different ids for each scte command.

**Comment by futzu** [comment]
Good point, let me think about how to fix it for as minute, and I'll update it this week.

**Comment by futzu** [comment]
I just saw your pull request, cool. Let me check it out.

**Comment by futzu** [comment]
Released . Good catch man, thank you.
