### ISSUE TITLE
New: --replay should not include -c by default

### ISSUE THREAD

**Issue by alfonsosiloniz** [futzu/x9k3#24]
After adding the -c option to being able to continue a previously generated m3u8, the replay option included this option by default.

IMHO replay is an option that implies the usage of one file to produce a live feed. Not necesarily that means the previous content in the output directory is meaningful. 

I would suggest to decouple --replay and -c, so if someone needs it for replay, can add it explicitely

**Comment by futzu** [comment]
I see what you're saying , **we need to not continue the first time**, so we don't pick up old stuff. That makes sense. 
Give a minute, I got to run a bunch of stuff up to UPS to return before the end of today.

Good catch man. 

Adrian

**Comment by futzu** [comment]
You good on this?

**Comment by alfonsosiloniz** [comment]
Hi @futzu 

Thanks for all the effort. 

I think I didn´t explain the issue correctly, so this is why the changes are not fullfilling the need. Completely my fault

As I don´t want you to get confused, I will close this issue, and will open a new one with a long description of the issue, the tests I am doing, and what it should be, IMHO, the expected result for the replay functionality to work correctly. I hope that will help.
