### ISSUE TITLE
paypal account

### ISSUE THREAD

**Issue by cooliobr** [futzu/x9k3#30]
hi my brother.
you have PayPal account? or BTC/ETH ?
I need to sent some Christmas gift

**Comment by futzu** [comment]
Let me find my PAyPal, I got cash app. 

What is your schedule like tomorrow? 
I have the whole day open if we have any issues to sort out.

Adrian

**Comment by cooliobr** [comment]
Adrian, tomorrow I on road, but I can send money by swift too, no problem.

**Comment by futzu** [comment]
a@slo.me is me. Thank you man. 
Get the new x9k3, it is sweet. 0.2.41.

**Comment by futzu** [comment]
I'm closing because you obviously aaren't using it.

**Comment by cooliobr** [comment]
> [a@slo.me](mailto:a@slo.me) is me. Thank you man.
> Get the new x9k3, it is sweet. 0.2.41.

thanks bro, sorry for this small amount, but it is my first one.
