### ISSUE TITLE
How to use in hls?

### ISSUE THREAD

**Issue by LuizStSantos** [futzu/x9k3#32]
I'm new to the stream business, I still don't understand it very well, I have a hls stream http://localhost:8787/live/stream-1080p.m3u8 and I want to send a commercial ad signal inside it, what would that be like? this would be for the person to overlap this stream with their commercial

**Comment by futzu** [comment]
Dude, I don't have to explain everything , you need to do your homework, this is not a beginners tool.

**Comment by cooliobr** [comment]
Luiz, você precisa conversar com um SSAI para te fornecer acesso a plataforma de ad-replacement

**Comment by LuizStSantos** [comment]
> Luiz, você precisa conversar com um SSAI para fornecer acesso à plataforma de substituição de anúncios

Não sou eu que vou substituir a única coisa que preciso e fazer e mandar um sinal para que possam substituir o break comercial

**Comment by cooliobr** [comment]
> > Luiz, você precisa conversar com um SSAI para fornecer acesso à plataforma de substituição de anúncios
> 
> Não sou eu que vou substituir a única coisa que preciso e fazer e mandar um sinal para que possam substituir o break comercial, que no caso eu vou passar um aqui meu e lá eles vão passar o deles

então é só usar o x9k3, não tem segredo
